---
title: "Meta analysis"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
date: "`r Sys.Date()`"
---

```{r loading packages, include=FALSE}
library(conflicted)
library(tidyverse)
library(janitor)
library(gtsummary)
library(broomExtra)
library(RColorBrewer)
library(knitr)
library(flextable)
library(meta)
library(metafor)
library(lme4)
library(gtsummary)
library(gee)
library(geepack)
library(glm2)
#library(broom.mixed)
library(DT)
#install.packages("logistf")
library(logistf)
conflicts_prefer(dplyr::filter, broomExtra::tidy)
```

```{r include=FALSE}
#fig.pos='htb!',
opts_chunk$set(tidy.opts=list(width.cutoff=50),
               tidy=TRUE,echo = FALSE,fig.pos='htb!',
               fig.align='center',
               fig.width=6, fig.height=3.2,warning = FALSE,
               message = FALSE,
               error = TRUE)
```

```{r loading data}
load("Y:/Systematic Reviews/iCOMP/11. Data/Analysis/Analysis for resusc with cord intact/merged data/merged dataset/combined_df_cordintact.rda")

#compute inf_sepsis as a binary outcome per SAP definition
final_df <- final_df %>% mutate(hypothermia = ifelse(final_df$temp <36.5, 1, 0) %>% as.factor())

final_df <- final_df %>% mutate (inf_sepsis = inf_sepsis %>% as_factor(), GA = (GA_weeks + (GA_days/7)) %>% as.numeric(), mat_ID = if_else(is.na(mat_ID), paste0("uid_", row_number()),                   as.character(mat_ID)))

mortality_count <- final_df %>% group_by(Trial_id,treatment_new) %>% 
  mutate(n = n()) %>%# filter(Trial_id == "india_datta_2017")
  ungroup %>% 
  # filter(inf_death == 1) %>% 
  group_by(Trial_id,treatment_new) %>% 
  mutate(n_event = sum(inf_sepsis == 1,na.rm = TRUE)) %>% 
  ungroup() %>% 
  distinct(Trial_id,treatment_new,n,n_event) %>%
  pivot_wider(names_from = treatment_new,
              values_from = c(n,n_event)) %>% 
  select(Trial_id,
        n_event_cordintact, n_cordintact, n_event_control, n_control) 
 
counts <- data.frame( ai= mortality_count$n_event_cordintact,
bi =mortality_count$n_cordintact- mortality_count$n_event_cordintact,
n1i =mortality_count$n_cordintact,
ci=mortality_count$n_event_control,
di = mortality_count$n_control- mortality_count$n_event_control,
n2i = mortality_count$n_control,
Trial_id=paste(mortality_count$Trial_id, sep=" "))

```

```{r}
tidy.logistf <- function(x,conf.int = TRUE, conf.level = 0.95, ...) {
  
  trash <- utils::capture.output(s <- summary(x))
  ret <- tibble(
    term = names(s$coefficients),
    estimate = s$coefficients,
    std.error = sqrt(diag(s$var)),
    p.value = s$prob)
  
  if (conf.int) {
    if (conf.level != x$conflev) {
      warning("Models of class `logistf` do not allow `glance` to modify the alpha level after fitting the model. Please use the `alpha` argument of the `logistf::logistf` function.")
    }
    
    ci <- confint(x, level = conf.level)
    ci <- tibble::tibble(
      term = row.names(ci),
      conf.low = ci[, 1],
      conf.high = ci[, 2])
    
    ret <- dplyr::left_join(ret, ci, by = "term")
  }
  
  ret
}

mortality_gee <-
  final_df %>% 
  filter(!is.na(inf_sepsis)) %>% 
  mutate(inf_sepsis = inf_sepsis %>%
           as.character %>% as.numeric(),
           mat_ID = mat_ID %>% as.factor()) %>% 
    arrange(mat_ID)

#egypt_allam_2018_two <- logistf(inf_sepsis ~ treatment_new + GA, data = final_df [final_df$Trial_id == "egypt_allam_2018",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="egypt_allam_2018")

uk_duley_2017_two <- logistf(inf_sepsis ~ treatment_new + GA, data = final_df [final_df$Trial_id == "uk_duley_2017",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="uk_duley_2017")

ireland_finn_2019_two <- logistf(inf_sepsis ~ treatment_new + GA, data = final_df [final_df$Trial_id == "ireland_finn_2019",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="ireland_finn_2019")

#italy_pratesi_2018_two <- logistf(inf_sepsis ~ treatment_new + GA, data = final_df [final_df$Trial_id == "italy_pratesi_2018",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="italy_pratesi_2018")

#india_raina_2020_two <-
  #geeglm(inf_sepsis ~ treatment_new  + GA,
      #data =
          #mortality_gee[mortality_gee$Trial_id == 
                                  #"india_raina_2020",],
      #id = mat_ID,
      #family = binomial("logit"),
      #control = geese.control(maxit = 100)
      #) %>%
  #tidy() %>% 
  #mutate(Trial_id = "india_raina_2020")


usa_katheria_nric_2016_two <-
  geeglm(inf_sepsis ~ treatment_new  + GA,
      data =
          mortality_gee[mortality_gee$Trial_id == 
                                  "usa_katheria_nric_2016",],
      id = mat_ID,
      family = binomial("logit"),
      control = geese.control(maxit = 100)
      ) %>%
  tidy() %>% 
  mutate(Trial_id = "usa_katheria_nric_2016")

merged_two <- 
  dplyr::bind_rows(#egypt_allam_2018_two,
            #india_raina_2020_two,
            ireland_finn_2019_two,
            #italy_pratesi_2018_two,
            uk_duley_2017_two,
            usa_katheria_nric_2016_two)%>% 
  filter(term == "treatment_newcordintact") %>% 
    arrange(Trial_id)
```

```{r two stage meta analysis}
mortality_count_merged <- 
  counts %>% 
  left_join(merged_two,by = "Trial_id")


IPD_death_df <- 
  escalc(yi = estimate, 
         sei = std.error, 
         ai= n_events_UCM,
         bi = n_UCM - n_event_UCM, 
         n1i = n_UCM ,
         ci= n_event_DCC, 
         di = n_DCC - n_event_DCC, 
         n2i = n_DCC,
         data = mortality_count_merged)
IPD_death_df <- IPD_death_df %>% mutate(alloc = rev(seq(2, (nrow(IPD_death_df)+1))) )

res.IPD <- rma(yi, vi,  data = IPD_death_df, method="FE",
         ai= n_events_cordintact,
           bi = n_cordintact - n_event_cordintact, 
           n1i = n_cordintact,
           ci= n_event_control, 
           di = n_control  - n_event_control, 
           n2i = n_control, 
           slab=paste((mortality_count_merged$Trial_id), sep=" "))
predict (res.IPD, transf = exp, digits=2)
```

```{r fig.height= 10, fig.width=17, dpi=400}
data_height <- nrow(IPD_death_df)

#change the left bound after you have run the forest plot once
left_bound <- -8.5
#change the right bound after you have run the forest plot once
right_bound <-6

mlabfun <- function(text, res) {
   list(bquote(paste(.(text),
      " (Q = ", .(formatC(res$QE, digits=2, format="f")),
      ", df = ", .(res$k - res$p),
      ", p ", .(metafor:::.pval(res$QEp, digits=2, showeq=TRUE, sep=" ")), "; ",
      I^2, " = ", .(formatC(res$I2, digits=1, format="f")), "%, ",
      tau^2, " = ", .(formatC(res$tau2, digits=2, format="f")), ")")))}


 #keep in trials with 0 0 events in
  options(na.action = "na.pass")

sav <- forest(res.IPD, atransf=exp, addpred=TRUE, rows = c(1:(data_height)), xlab ="Odds ratio (log scale)",mlab=mlabfun("Adjusted Two Stage FE Model", res.IPD), order=IPD_death_df$alloc, 
                ylim=c(-2.3,(data_height +3)), xlim=c(left_bound,right_bound),
                alim = c(log(0.05), log(20)), cex=1.3, showweights = TRUE,
                ilab=cbind(counts$ai, counts$bi, counts$ci, counts$di), ilab.xpos=seq(-5.8,-3.8, length = 4), slab =res.IPD$slab,  header = FALSE, annotate = TRUE)

par(xpd=NA)
  
   text(left_bound, data_height+3.5, pos=4, cex=1.3, c("Resuscitation with cord intact Meta-analysis - late onset sepsis"), font = 4)
  
  text(sav$ilab.xpos, (data_height+2), pos=1, c("Events","Total","Events","Total"), cex = 1.1, font =3)
  
text(c(mean(sav$ilab.xpos[1:2]),mean(sav$ilab.xpos[3:4])), data_height+3, c("Cord intact","Control"), pos=1, cex=1.3)

text(c(log(0.05),log(20)), -2.2, pos=1, c("Favours Cord intact", "Favours Control"), cex=1.3)
text(6,                     9, "Odds Ratio [95% CI]", cex=1.3, pos = 2)
text(-7.8,                     9, "Study", cex=1.3, pos = 2)
 ### add 'Not estimable' for study with missing log odds ratio
  #I've made it so it doesn't include the bottom line (totals)
  text(sav$textpos[2], data_height+1-which(is.na(IPD_death_df[1:nrow(IPD_death_df)-1,]$yi)), "Not estimable", pos=2, cex=1.3)
```