---
title: "Meta analysis"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
date: "`r Sys.Date()`"
---

```{r loading packages, include=FALSE}
library(conflicted)
library(tidyverse)
library(janitor)
library(gtsummary)
library(RColorBrewer)
library(knitr)
library(flextable)
library(meta)
library(metafor)
library(lme4)
library(gtsummary)
library(gee)
library(geepack)
library(glm2)
library(broom.mixed)
library(DT)
#install.packages("logistf")
library(logistf)
conflicts_prefer(dplyr::filter, broomExtra::tidy)
```

```{r include=FALSE}
#fig.pos='htb!',
opts_chunk$set(#tidy.opts=list(width.cutoff=50),
               tidy=TRUE,echo = FALSE,fig.pos='htb!',
               fig.align='center',
               #fig.width=6, fig.height=3.2,
               cache = TRUE,
               warning = FALSE,
               message = FALSE,
               error = TRUE)
```

```{r loading data}
load("Y:/Systematic Reviews/iCOMP/11. Data/Data from trials/combined_df.rda")

source("Y:\\Systematic Reviews\\iCOMP\\11. Data\\Analysis\\Sol_forrest_plot_tables\\functions_for_forest_plots1.R")

final_df[final_df$Trial_id=="australia_tarnow-mordi_apts_2017",]$Trial_id <- "aus_tarnow_mordi_2017"
#final_df[final_df$Trial_id=="egypt_nour_2020",]$Trial_id <- "egypt_yunis_2021"

final_df <- final_df %>% mutate (death_discharge_new = death_discharge_new %>% as_factor())
final_df <- final_df %>% filter (!Trial_id =="china_hua_2010")
```

```{r}

summary_ICC_DCC <- 
  final_df %>% 
  mutate(treatment_cat = 
           treatment_cat %>%
           fct_recode("ICC" = "1",
                      "DCC" = "2",
                      "DCC" = "3",
                      "DCC" = "4",
                      "CM" ="5",
                      "CM" ="6",
                      "CM" ="7",
                      "CM" ="8",
                      "DCC" = "9")) %>% 
  ungroup %>% mutate(GA_days = GA_days %>% replace_na(3.5)) %>%  
  filter(!is.na(GA_weeks)) %>% 
  mutate(GA = (GA_weeks + (GA_days/7)) %>% as.numeric(), mat_ID = if_else(is.na(mat_ID), paste0("uid_", row_number()),                   as.character(mat_ID)))



ICC_DCC <- 
  summary_ICC_DCC  %>%
  select(Trial_id,treatment_cat,death_discharge_new,GA, mat_ID) %>% 
  filter(treatment_cat %in% c("ICC","DCC")) %>% 
  mutate(treatment_cat = 
           treatment_cat %>% fct_drop()) %>% 
  group_by(Trial_id) %>% 
  filter(sum(treatment_cat == "ICC") > 0 & 
           sum(treatment_cat == "DCC") > 0)  %>% ungroup %>% arrange(Trial_id)


mortality_ICC_DCC_count <- ICC_DCC %>% group_by(Trial_id,treatment_cat) %>% 
  mutate(n = n()) %>%# filter(Trial_id == "india_datta_2017")
  ungroup %>% 
  # filter(inf_death == 1) %>% 
  group_by(Trial_id,treatment_cat) %>% 
  mutate(n_event = sum(death_discharge_new == 1,na.rm = TRUE)) %>% 
  ungroup() %>% 
  distinct(Trial_id,treatment_cat,n,n_event) %>%
  pivot_wider(names_from = treatment_cat,
              values_from = c(n,n_event)) %>% 
  select(Trial_id,
        n_event_ICC, n_ICC, n_event_DCC, n_DCC) 
 
double_zero_trials <-mortality_ICC_DCC_count %>% filter(n_event_ICC == 0 & n_event_DCC == 0) %>% pull(Trial_id) %>% as.vector()

#mortality_ICC_DCC_count <-mortality_ICC_DCC_count %>% filter(!Trial_id %in% double_zero_trials)

counts <- data.frame( ai= mortality_ICC_DCC_count$n_event_DCC,
bi =mortality_ICC_DCC_count$n_DCC- mortality_ICC_DCC_count$n_event_DCC,
n1i =mortality_ICC_DCC_count$n_DCC,
ci=mortality_ICC_DCC_count$n_event_ICC,
di = mortality_ICC_DCC_count$n_ICC- mortality_ICC_DCC_count$n_event_ICC,
n2i = mortality_ICC_DCC_count$n_ICC,
Trial_id=paste(mortality_ICC_DCC_count$Trial_id, sep=" "))

totals_df <- data.frame(ai = sum(counts$ai, na.rm=T),
                          bi = sum(counts$bi, na.rm=T),
                          n1i = sum(counts$n1i, na.rm=T),
                          ci = sum(counts$ci, na.rm=T),
                          di = sum(counts$di, na.rm=T),
                          n2i = sum(counts$n2i, na.rm=T),
                           Trial_id= "Overall")

df <- rbind(counts, totals_df)

```

```{r fitting regression model for two stage}

tidy.logistf <- function(x,conf.int = TRUE, conf.level = 0.95, ...) {
  
  trash <- utils::capture.output(s <- summary(x))
  ret <- tibble(
    term = names(s$coefficients),
    estimate = s$coefficients,
    std.error = sqrt(diag(s$var)),
    p.value = s$prob)
  
  if (conf.int) {
    if (conf.level != x$conflev) {
      warning("Models of class `logistf` do not allow `glance` to modify the alpha level after fitting the model. Please use the `alpha` argument of the `logistf::logistf` function.")
    }
    
    ci <- confint(x, level = conf.level)
    ci <- tibble::tibble(
      term = row.names(ci),
      conf.low = ci[, 1],
      conf.high = ci[, 2])
    
    ret <- dplyr::left_join(ret, ci, by = "term")
  }
  
  ret
}

mortality_ICC_DCC_gee <-
  ICC_DCC %>% 
  filter(!is.na(death_discharge_new)) %>% 
  mutate(death_discharge_new = death_discharge_new %>%
           as.character %>% as.numeric(),
         treatment_cat = treatment_cat %>% 
           relevel(ref = "ICC"),
         # sex = sex %>% as.factor %>% relevel(ref = "1"),
         mat_ID = mat_ID %>% as.factor()) %>% 
  # select(Trial_id,infant_ID,mat_ID)
  arrange(mat_ID)

aus_tarnow_mordi_2017_two <-
  geeglm(death_discharge_new ~ treatment_cat  + GA,
      data =
          mortality_ICC_DCC_gee[mortality_ICC_DCC_gee$Trial_id == 
                                  "aus_tarnow_mordi_2017",],
      id = mat_ID,
      family = binomial("logit"),
      control = geese.control(maxit = 100)
      ) %>%
  tidy() %>% 
  mutate(Trial_id = "aus_tarnow_mordi_2017")

canada_murphy_two <- logistf (death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "canada_murphy_2007",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="canada_murphy_2007")

egypt_allam_2018_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "egypt_allam_2018",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="egypt_allam_2018")

#egypt_yunis_2021_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "egypt_yunis_2021",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="egypt_yunis_2021")
egypt_nour_2020_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "egypt_nour_2020",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="egypt_nour_2020")

india_agarwal_2019_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "india_agarwal_2019",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="india_agarwal_2019")

india_datta_2017_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "india_datta_2017",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="india_datta_2017")

india_ranjit_2013_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "india_ranjit_2013",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="india_ranjit_2013")

israel_kugelman_2007_two <- logistf (death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "israel_kugelman_2007",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="israel_kugelman_2007")

spain_carbonell_2014_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "spain_carbonell_2014",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="spain_carbonell_2014")

spain_depaco_2011_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "spain_depaco_2011",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="spain_depaco_2011")

uk_duley_2017_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "uk_duley_2017",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="uk_duley_2017")

usa_backes_2016_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "usa_backes_2016",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="usa_backes_2016")

usa_oh_2011_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "usa_oh_2011",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="usa_oh_2011")

merged_two <- 
  dplyr::bind_rows(aus_tarnow_mordi_2017_two,canada_murphy_two,
            egypt_nour_2020_two,
            egypt_allam_2018_two, india_agarwal_2019_two, india_datta_2017_two,
            india_ranjit_2013_two,
            israel_kugelman_2007_two,
            spain_carbonell_2014_two,
            spain_depaco_2011_two,usa_backes_2016_two,
            uk_duley_2017_two,
            usa_oh_2011_two)  %>% 
  filter(term == "treatment_catDCC") %>% 
    arrange(Trial_id)

```

```{r eval=FALSE, include=FALSE}
final_df$Trial_id %>% 
           str_replace_all("_"," ") %>%
           str_to_title() %>% 
           str_replace(" ", " (") %>%
           str_replace("$",")") %>% 
           str_replace("Aus","Australia") %>% 
           str_replace("Uk","UK") %>% 
           str_replace("Usa","USA") %>% 
           str_replace("Turkey","Türkiye") %>% 
           replace("Overall)","Overall") %>% 
  unique()
```


```{r two stage meta analysis}
mortality_ICC_DCC_count_merged <- 
  df %>% 
  left_join(merged_two,by = "Trial_id") %>%
  mutate(Trial_id_new = 
           Trial_id %>% 
           str_replace_all("_"," ") %>%
           str_to_title() %>% 
           str_replace(" ", " (") %>%
           str_replace("$",")") %>% 
           str_replace("Aus","Australia") %>% 
           str_replace("Uk","UK") %>% 
           str_replace("Usa","USA") #%>% 
           # str_replace("Turkey","Türkiye")# %>% 
           #replace("Overall)","Overall")
           ) %>% 
  mutate(Trial_id_new = Trial_id_new %>% replace(Trial_id_new == "Overall)","Overall"))

IPD_icc_dcc_death_df <- 
  escalc(yi = estimate, 
         sei = std.error, 
         ai= n_events_DCC,
         bi = n_DCC - n_event_DCC, 
         n1i = n_DCC ,
         ci= n_event_ICC, 
         di = n_ICC - n_event_ICC, 
         n2i = n_ICC,
         data = mortality_ICC_DCC_count_merged)

IPD_icc_dcc_death_df <- IPD_icc_dcc_death_df %>% arrange (IPD_icc_dcc_death_df$std.error)

IPD_icc_dcc_death_df <- IPD_icc_dcc_death_df %>% mutate(alloc = rev(seq(2, (nrow(IPD_icc_dcc_death_df)+1))) )

res.IPD <- rma(yi, vi,  data = IPD_icc_dcc_death_df, method="FE",
         ai= n_events_DCC,
           bi = n_DCC - n_event_DCC, 
           n1i = n_DCC ,
           ci= n_event_ICC, 
           di = n_ICC  - n_event_ICC, 
           n2i = n_ICC, 
           slab=paste((IPD_icc_dcc_death_df$Trial_id_new), sep=" "))

predict (res.IPD, transf = exp, digits=2)

res.IPD1 <- leave1out(res.IPD)

```

```{r fig.height= 12, fig.width=18, dpi=500}

rma_poly <- res.IPD

#change the left bound after you have run the forest plot once
left_bound <- -2.5
#change the right bound after you have run the forest plot once
right_bound <-2

mlabfun <- function(text, res) {
   list(bquote(paste(.(text),
      " (Q = ", .(formatC(res$QE, digits=2, format="f")),
      ", df = ", .(res$k - res$p),
      ", p ", .(metafor:::.pval(res$QEp, digits=2, showeq=TRUE, sep=" ")), "; ",
      I^2, " = ", .(formatC(res$I2, digits=1, format="f")), "%, ",
      tau^2, " = ", .(formatC(res$tau2, digits=2, format="f")), ")")))}


 sav <-forest(res.IPD1$estimate, sei=res.IPD1$se, 
              atransf = exp, 
              header=FALSE, 
              #rows = c(1:(data_height)), 
              xlab="Leave One Out Estimate",
              #mlab = "Adjusted Two Stage Fixed Effect Model",
              xlim = c(left_bound, right_bound),
              ylim = c(-0.5, 15.5),
              slab = res.IPD1$slab, 
              cex = 1.3,#showweights = TRUE, 
              refline=coef(res.IPD), 
              annotate = TRUE#,
              # fonts = 15
              )
 par(xpd = NA)
 

  text(left_bound, 15, pos=4, cex=1.3, c("Deferred cord clamping (DCC) versus immediate cord clamping (ICC) for primary outcome death before discharge (leaving one out)"), font = 4)

#text(c(-1,0.1), 0, pos=1, c("Favours DCC", "Favours ICC"), cex=1.3)
text(2,                     14.5, "Odds Ratio", cex=1.3, pos = 2)
text(2,                     14,"[95% CI]", cex=1.3, pos = 2)
#text(1.5,                     14,"Weight", cex=1.3, pos = 2)
text(-2.2,                     14, "Study", cex=1.3, pos = 2)
 ### add 'Not estimable' for study with missing log odds ratio
  #I've made it so it doesn't include the bottom line (totals)

addpoly(rma_poly, row=0, mlab="")    
```
