---
title: "Meta analysis"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
date: "`r Sys.Date()`"
---

```{r loading packages, include=FALSE}
library(conflicted)
library(tidyverse)
library(janitor)
library(gtsummary)
library(broomExtra)
library(RColorBrewer)
library(knitr)
library(flextable)
library(meta)
library(metafor)
library(lme4)
library(gtsummary)
library(gee)
library(geepack)
library(glm2)
library(DT)
#install.packages("logistf")
library(logistf)
conflicts_prefer(dplyr::filter, broomExtra::tidy)
```

```{r include=FALSE}
#fig.pos='htb!',
opts_chunk$set(tidy.opts=list(width.cutoff=50),
               tidy=TRUE,echo = FALSE,fig.pos='htb!',
               fig.align='center',
               fig.width=6, fig.height=3.2,warning = FALSE,
               message = FALSE,
               error = TRUE)
```

```{r loading data}
load("Y:/Systematic Reviews/iCOMP/11. Data/Data from trials/combined_df.rda")

final_df[final_df$Trial_id=="australia_tarnow-mordi_apts_2017",]$Trial_id <- "aus_tarnow_mordi_2017"

final_df <- final_df %>% mutate (death_discharge_new = death_discharge_new %>% as_factor())
```

```{r}

summary_ICC_UCM <- 
  final_df %>% 
  mutate(treatment_cat = 
           treatment_cat %>%
           fct_recode("ICC" = "1",
                      "DCC" = "2",
                      "DCC" = "3",
                      "DCC" = "4",
                      "UCM" ="5",
                      "UCM" ="6",
                      "UCM" ="7",
                      "UCM" ="8",
                      "DCC" = "9")) %>% 
  ungroup %>% mutate(GA_days = GA_days %>% replace_na(3.5)) %>%  
  filter(!is.na(GA_weeks)) %>% 
  mutate(GA = (GA_weeks + (GA_days/7)) %>% as.numeric(), mat_ID = if_else(is.na(mat_ID), paste0("uid_", row_number()),                   as.character(mat_ID)))



ICC_UCM <- 
  summary_ICC_UCM  %>%
  select(Trial_id,treatment_cat,death_discharge_new,GA, mat_ID) %>% 
  filter(treatment_cat %in% c("ICC","UCM")) %>% 
  mutate(treatment_cat = 
           treatment_cat %>% fct_drop()) %>% 
  group_by(Trial_id) %>% 
  filter(sum(treatment_cat == "ICC") > 0 & 
           sum(treatment_cat == "UCM") > 0)  %>% ungroup %>% arrange(Trial_id)


mortality_ICC_UCM_count <- ICC_UCM %>% group_by(Trial_id,treatment_cat) %>% 
  mutate(n = n()) %>%# filter(Trial_id == "india_datta_2017")
  ungroup %>% 
  # filter(inf_death == 1) %>% 
  group_by(Trial_id,treatment_cat) %>% 
  mutate(n_event = sum(death_discharge_new == 1,na.rm = TRUE)) %>% 
  ungroup() %>% 
  distinct(Trial_id,treatment_cat,n,n_event) %>%
  pivot_wider(names_from = treatment_cat,
              values_from = c(n,n_event)) %>% 
  select(Trial_id,
        n_event_ICC, n_ICC, n_event_UCM, n_UCM) 
 
double_zero_trials <-mortality_ICC_UCM_count %>% filter(n_event_ICC == 0 & n_event_UCM == 0) %>% pull(Trial_id) %>% as.vector()

#mortality_ICC_DCC_count <-mortality_ICC_DCC_count %>% filter(!Trial_id %in% double_zero_trials)

counts <- data.frame( ai= mortality_ICC_UCM_count$n_event_UCM,
bi =mortality_ICC_UCM_count$n_UCM- mortality_ICC_UCM_count$n_event_UCM,
n1i =mortality_ICC_UCM_count$n_UCM,
ci=mortality_ICC_UCM_count$n_event_ICC,
di = mortality_ICC_UCM_count$n_ICC- mortality_ICC_UCM_count$n_event_ICC,
n2i = mortality_ICC_UCM_count$n_ICC,
Trial_id=paste(mortality_ICC_UCM_count$Trial_id, sep=" "))

```


```{r fitting regression model for two stage}

tidy.logistf <- function(x,conf.int = TRUE, conf.level = 0.95, ...) {
  
  trash <- utils::capture.output(s <- summary(x))
  ret <- tibble(
    term = names(s$coefficients),
    estimate = s$coefficients,
    std.error = sqrt(diag(s$var)),
    p.value = s$prob)
  
  if (conf.int) {
    if (conf.level != x$conflev) {
      warning("Models of class `logistf` do not allow `glance` to modify the alpha level after fitting the model. Please use the `alpha` argument of the `logistf::logistf` function.")
    }
    
    ci <- confint(x, level = conf.level)
    ci <- tibble::tibble(
      term = row.names(ci),
      conf.low = ci[, 1],
      conf.high = ci[, 2])
    
    ret <- dplyr::left_join(ret, ci, by = "term")
  }
  
  ret
}

mortality_ICC_UCM_gee <-
  ICC_UCM %>% 
  filter(!is.na(death_discharge_new)) %>% 
  mutate(death_discharge_new = death_discharge_new %>%
           as.character %>% as.numeric(),
         treatment_cat = treatment_cat %>% 
           relevel(ref = "ICC"),
         # sex = sex %>% as.factor %>% relevel(ref = "1"),
         mat_ID = mat_ID %>% as.factor()) %>% 
  # select(Trial_id,infant_ID,mat_ID)
  arrange(mat_ID)

canada_el_naggar_2018_two <-
  geeglm(death_discharge_new ~ treatment_cat  + GA,
                   id = mat_ID,
      data = mortality_ICC_UCM_gee[mortality_ICC_UCM_gee$Trial_id == 
                                  "canada_el-naggar_2018",],
        family = binomial("logit")) %>%
  tidy() %>% 
  mutate(Trial_id = "canada_el-naggar_2018")

china_xie_2020_two <- logistf (death_discharge_new ~ treatment_cat + GA, data = ICC_UCM [ICC_UCM$Trial_id == "china_xie_2020",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="china_xie_2020")

india_varanattu_2017_two <-
  geeglm(death_discharge_new ~ treatment_cat  + GA,
      data =
          mortality_ICC_UCM_gee[mortality_ICC_UCM_gee$Trial_id == 
                                  "india_varanattu_2017",],
      id = mat_ID,
      family = binomial("logit"),
      control = geese.control(maxit = 100)
      ) %>%
  tidy() %>% 
  mutate(Trial_id = "india_varanattu_2017")

ireland_finn_2019_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_UCM [ICC_UCM$Trial_id == "ireland_finn_2019",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="ireland_finn_2019")

japan_hosono_2008_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_UCM [ICC_UCM$Trial_id == "japan_hosono_2008",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="japan_hosono_2008")

japan_hosono_2016_two <-
  geeglm(death_discharge_new ~ treatment_cat  + GA,
      data =
          mortality_ICC_UCM_gee[mortality_ICC_UCM_gee$Trial_id == 
                                  "japan_hosono_2016",],
      id = mat_ID,
      family = binomial("logit"),
      control = geese.control(maxit = 100)
      ) %>%
  tidy() %>% 
  mutate(Trial_id = "japan_hosono_2016")

taiwan_shen_2018_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_UCM [ICC_UCM$Trial_id == "taiwan_shen_2018",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="taiwan_shen_2018") 

thailand_tanthawat_2016_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_UCM [ICC_UCM$Trial_id == "thailand_tanthawat_2016",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="thailand_tanthawat_2016")

turkey_alan_2014_two <-
  geeglm(death_discharge_new ~ treatment_cat  + GA,
      data =
          mortality_ICC_UCM_gee[mortality_ICC_UCM_gee$Trial_id == 
                                  "turkey_alan_2014",],
      id = mat_ID,
      family = binomial("logit"),
      control = geese.control(maxit = 100)
      ) %>%
  tidy() %>% 
  mutate(Trial_id = "turkey_alan_2014")

usa_josephsen_2014_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_UCM [ICC_UCM$Trial_id == "usa_josephsen_2014",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="usa_josephsen_2014")

usa_katheria_2014_two <- logistf (death_discharge_new ~ treatment_cat + GA, data = ICC_UCM [ICC_UCM$Trial_id == "usa_katheria_2014",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="usa_katheria_2014")

usa_march_2011_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_UCM [ICC_UCM$Trial_id == "usa_march_2011",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="usa_march_2011")

usa_mercer_2018_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_UCM [ICC_UCM$Trial_id == "usa_mercer_2018",], family = binomial("logit")) %>% tidy() %>% mutate(Trial_id ="usa_mercer_2018")


merged_two <- 
  dplyr::bind_rows(canada_el_naggar_2018_two,
            china_xie_2020_two,
            india_varanattu_2017_two,
            ireland_finn_2019_two,
            japan_hosono_2008_two,
            japan_hosono_2016_two,
            taiwan_shen_2018_two,
            thailand_tanthawat_2016_two,
            turkey_alan_2014_two,
            usa_josephsen_2014_two,
            usa_katheria_2014_two,
            usa_march_2011_two,
            usa_mercer_2018_two)  %>% 
  filter(term == "treatment_catUCM") %>% 
    arrange(Trial_id)

```

```{r two stage meta analysis}
mortality_ICC_UCM_count_merged <- 
  counts %>% 
  left_join(merged_two,by = "Trial_id")


IPD_icc_UCM_death_df <- 
  escalc(yi = estimate, 
         sei = std.error, 
         ai= n_events_UCM,
         bi = n_UCM - n_event_UCM, 
         n1i = n_UCM ,
         ci= n_event_ICC, 
         di = n_ICC - n_event_ICC, 
         n2i = n_ICC,
         data = mortality_ICC_UCM_count_merged)
IPD_icc_UCM_death_df <- IPD_icc_UCM_death_df %>% mutate(alloc = rev(seq(2, (nrow(IPD_icc_UCM_death_df)+1))) )

res.IPD <- rma(yi, vi,  data = IPD_icc_UCM_death_df, method="FE",
         ai= n_events_UCM,
           bi = n_UCM - n_event_UCM, 
           n1i = n_UCM ,
           ci= n_event_ICC, 
           di = n_ICC  - n_event_ICC, 
           n2i = n_ICC, 
           slab=paste((mortality_ICC_UCM_count_merged$Trial_id), sep=" "))
predict (res.IPD, transf = exp, digits=2)
```

```{r one stage meta analysis}
final_df1 <- final_df
#coding maternal ID so there are less intercepts (all singletons on one intercept)
#maternal_ID
final_df1$mat_ID2 <- ifelse(final_df1$multiple==0,final_df1$mat_ID==0,final_df1$mat_ID)

#different method to code any maternal id that doesn't occur more than once on the same intercept
mat_ID3 <- final_df1 %>% group_by(mat_ID) %>% dplyr::summarise(freq = n())
mat_ID4 <- mat_ID3[mat_ID3$freq<2,]$mat_ID
mat_ID4 <- unlist(mat_ID4) %>% as.vector()
final_df1$mat_ID3 <- as.character(final_df1$mat_ID)
final_df1[final_df1$mat_ID3 %in% mat_ID4, ]$mat_ID3  <- "0"
final_df1[is.na(final_df1$mat_ID3),]$mat_ID3 <- "0"

#more maternal ID coding (not using the below however)
maternal_ID <- as.factor(as.numeric(as.factor(final_df1$mat_ID3)))
final_df1$mat_ID2 <-  as.character(as.factor(as.numeric(as.factor(final_df1$mat_ID))))
final_df1$mat_ID2 <- ifelse(is.na(final_df1$mat_ID2), paste0(final_df1$Trial_id, final_df1$infant_ID),final_df1$mat_ID2)
final_df1$mat_ID2 <-  as.factor(as.numeric(as.factor(final_df1$mat_ID2)))

#bringing GA_weeks and GA_days together to create GA total days
final_df1$GA_total_days <- ifelse(!is.na(final_df1$GA_days), final_df1$GA_weeks*7 + final_df1$GA_days, final_df1$GA_weeks+3)
# centering gestational age
final_df1$GA_total_days_centered <- final_df1$GA_total_days - mean(final_df1$GA_total_days, na.rm=T)

#coding sex and centering
final_df1$sex <- final_df1$sex%>% na_if("3")
final_df1$sex <- final_df1$sex %>% as.factor %>%   fct_recode("0" = "1","1" = "2") %>%  relevel(ref = "0")
final_df1$sex <- as.numeric(as.character(final_df1$sex))
final_df1$sex_centered <- final_df1$sex - mean(final_df1$sex, na.rm=T)
final_df1$sex_centered <- as.factor(as.character(final_df1$sex_centered))

final_df1 <- 
  final_df1 %>%
  group_by(Trial_id) %>%
  mutate(GA_total_days_centered_within =
           GA_total_days - mean(GA_total_days),
         GA_total_days_mean = mean(GA_total_days)) %>% 
  ungroup

#making trial IDs numbers in case we need
final_df1$Trial_id1 <- as.numeric(as.factor(final_df1$Trial_id))


##======================================================================================
#### coding ICC_UCM variable for pairwise comparison (collapsing groups)

final_df1$ICC_UCM <-  ifelse(grepl("5|6|7|8", final_df1$treatment_cat), 2,ifelse(final_df1$treatment_cat=="1",1, NA))

final_df1_ICC_UCM <- final_df1%>% filter(!is.na(ICC_UCM))  

final_df1_ICC_UCM <- final_df1_ICC_UCM %>%  group_by(Trial_id) %>%  filter(sum(ICC_UCM == 1) > 0 & 
           sum(ICC_UCM == 2) > 0) 

# make the outcome numeric (Need to make it a character first to avoid accidentally changing 0s to 1s)
final_df1$death_discharge_new <- as.numeric(as.character(final_df1$death_discharge_new))

#filtering double zero trials
final_df1 <- final_df1 %>% group_by(Trial_id) %>% filter(sum(death_discharge_new== "1", na.rm = T)>0) 

```

```{r one stage model}
# run the stage model (edit - change the outcome i.e., death_discharge_new)
# nested random intercept
one_stage_glmm_ICC_UCM  <- 
  glmer( death_discharge_new ~
           ICC_UCM  + 
          GA_total_days_centered_within +
           Trial_id +
           ( 1 | Trial_id/mat_ID3) - 1,
         data = final_df1,
         family = binomial(link = "logit"),
         control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
         
## no need to change the code below
one_stage_model <- one_stage_glmm_ICC_UCM  %>% 
  tidy(conf.int=TRUE,
       exponentiate=FALSE,
        effects="fixed"
       ) %>% 
  mutate(across(where(is.numeric),
                ~round(.,digit= 2))) 

 
one_stage_model_exp <- one_stage_glmm_ICC_UCM  %>% 
  tidy(conf.int=TRUE,
       exponentiate=TRUE,
        effects="fixed"
       ) %>% 
  mutate(across(where(is.numeric),
                ~round(.,digit= 4))) 


##print the exponentiated results for the one stage model
one_stage_model_exp[1,]
```


```{r}
one_stage_glmm_ICC_UCM %>% summary
```
Odds ratios results:
```{r}
one_stage_glmm_ICC_UCM %>% 
  tidy(conf.int=TRUE,
       exponentiate=TRUE,
        effects="fixed"
       ) %>% 
  mutate(across(where(is.numeric),~round(.,digit= 2)))

```

```{r fig.height= 10, fig.width=17, dpi=400}
data_height <- nrow(IPD_icc_UCM_death_df)

#change the left bound after you have run the forest plot once
left_bound <- -8.5
#change the right bound after you have run the forest plot once
right_bound <-6

rma_poly <- res.IPD

rma_poly$beta <- one_stage_model[1,]$estimate

rma_poly$ci.lb <- one_stage_model[1,]$conf.low
rma_poly$ci.ub <- one_stage_model[1,]$conf.high
rma_poly$vb <- ((rma_poly$ci.ub - rma_poly$ci.lb)/3.92)^2


mlabfun <- function(text, res) {
   list(bquote(paste(.(text),
      " (Q = ", .(formatC(res$QE, digits=2, format="f")),
      ", df = ", .(res$k - res$p),
      ", p ", .(metafor:::.pval(res$QEp, digits=2, showeq=TRUE, sep=" ")), "; ",
      I^2, " = ", .(formatC(res$I2, digits=1, format="f")), "%, ",
      tau^2, " = ", .(formatC(res$tau2, digits=2, format="f")), ")")))}


 #keep in trials with 0 0 events in
  options(na.action = "na.pass")

sav <- forest(res.IPD, atransf=exp, addpred=TRUE, rows = c(1:(data_height)), xlab ="Odds ratio (log scale)",mlab=mlabfun("Adjusted Two Stage FE Model", res.IPD), order=IPD_icc_UCM_death_df$alloc, 
                ylim=c(-2.3,(data_height +3)), xlim=c(left_bound,right_bound),
                alim = c(log(0.05), log(20)), cex=1.3, showweights = TRUE,
                ilab=cbind(counts$ai, counts$bi, counts$ci, counts$di), ilab.xpos=seq(-5.8,-3.8, length = 4), slab =res.IPD$slab,  header = FALSE, annotate = TRUE)

par(xpd=NA)
  
  addpoly(rma_poly, row=-2, mlab="")
  text(left_bound, -2, pos=4, cex=1.3, c("Adjusted One Stage FE Model"), font = 2)
  
  text(left_bound, data_height+3.5, pos=4, cex=1.3, c("ICC vs UCM Meta-analysis - Death before discharge"), font = 4)
  
  text(sav$ilab.xpos, (data_height+2), pos=1, c("Events","Total","Events","Total"), cex = 1.1, font =3)
  
text(c(mean(sav$ilab.xpos[1:2]),mean(sav$ilab.xpos[3:4])), data_height+3, c("ICC","UCM"), pos=1, cex=1.3)

text(c(log(0.05),log(20)), -2.2, pos=1, c("Favours UCM", "Favours ICC"), cex=1.3)
text(6,                     20, "Odds Ratio [95% CI]", cex=1.3, pos = 2)
text(-7.8,                     20, "Study", cex=1.3, pos = 2)
 ### add 'Not estimable' for study with missing log odds ratio
  #I've made it so it doesn't include the bottom line (totals)
  text(sav$textpos[2], data_height+1-which(is.na(IPD_icc_UCM_death_df[1:nrow(IPD_icc_UCM_death_df)-1,]$yi)), "Not estimable", pos=2, cex=1.3)
```