---
title: "Meta analysis"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
date: "`r Sys.Date()`"
---

```{r loading packages, include=FALSE}
library(conflicted)
library(tidyverse)
library(janitor)
library(gtsummary)
library(RColorBrewer)
library(knitr)
library(flextable)
library(meta)
library(metafor)
library(lme4)
library(gtsummary)
library(gee)
library(geepack)
library(glm2)
library(broom.mixed)
library(DT)
#install.packages("logistf")
library(logistf)
conflicts_prefer(dplyr::filter, broomExtra::tidy)
```

```{r include=FALSE}
#fig.pos='htb!',
opts_chunk$set(tidy.opts=list(width.cutoff=50),
               tidy=TRUE,echo = FALSE,fig.pos='htb!',
               fig.align='center',
               fig.width=6, fig.height=3.2,warning = FALSE,
               message = FALSE,
               error = TRUE)
```

```{r loading data}
load("Y:/Systematic Reviews/iCOMP/11. Data/Data from trials/combined_df.rda")
load("Y:/Systematic Reviews/iCOMP/11. Data/Data_merging/final mergerd AD/combined_df_ad.rda")

source("Y:\\Systematic Reviews\\iCOMP\\11. Data\\Analysis\\Sol_forrest_plot_tables\\functions_for_forest_plots1.R")

final_df[final_df$Trial_id=="australia_tarnow-mordi_apts_2017",]$Trial_id <- "aus_tarnow_mordi_2017"

final_df <- final_df %>% mutate (death_discharge_new = death_discharge_new %>% as_factor())
final_df <- final_df %>% filter (!Trial_id =="china_hua_2010")
```

```{r}

summary_ICC_DCC <- 
  final_df %>% 
  mutate(treatment_cat = 
           treatment_cat %>%
           fct_recode("ICC" = "1",
                      "DCC" = "2",
                      "DCC" = "3",
                      "DCC" = "4",
                      "CM" ="5",
                      "CM" ="6",
                      "CM" ="7",
                      "CM" ="8",
                      "DCC" = "9")) %>% 
  ungroup %>% mutate(GA_days = GA_days %>% replace_na(3.5)) %>%  
  filter(!is.na(GA_weeks)) %>% 
  mutate(GA = (GA_weeks + (GA_days/7)) %>% as.numeric(), mat_ID = if_else(is.na(mat_ID), paste0("uid_", row_number()),                   as.character(mat_ID)))



ICC_DCC <- 
  summary_ICC_DCC  %>%
  select(Trial_id,treatment_cat,death_discharge_new,GA, mat_ID) %>% 
  filter(treatment_cat %in% c("ICC","DCC")) %>% 
  mutate(treatment_cat = 
           treatment_cat %>% fct_drop()) %>% 
  group_by(Trial_id) %>% 
  filter(sum(treatment_cat == "ICC") > 0 & 
           sum(treatment_cat == "DCC") > 0)  %>% ungroup %>% arrange(Trial_id)


mortality_ICC_DCC_count <- ICC_DCC %>% group_by(Trial_id,treatment_cat) %>% 
  mutate(n = n()) %>%# filter(Trial_id == "india_datta_2017")
  ungroup %>% 
  # filter(inf_death == 1) %>% 
  group_by(Trial_id,treatment_cat) %>% 
  mutate(n_event = sum(death_discharge_new == 1,na.rm = TRUE)) %>% 
  ungroup() %>% 
  distinct(Trial_id,treatment_cat,n,n_event) %>%
  pivot_wider(names_from = treatment_cat,
              values_from = c(n,n_event)) %>% 
  select(Trial_id,
        n_event_ICC, n_ICC, n_event_DCC, n_DCC) 
 
double_zero_trials <-mortality_ICC_DCC_count %>% filter(n_event_ICC == 0 & n_event_DCC == 0) %>% pull(Trial_id) %>% as.vector()

#mortality_ICC_DCC_count <-mortality_ICC_DCC_count %>% filter(!Trial_id %in% double_zero_trials)

counts <- data.frame( ai= mortality_ICC_DCC_count$n_event_DCC,
bi =mortality_ICC_DCC_count$n_DCC- mortality_ICC_DCC_count$n_event_DCC,
n1i =mortality_ICC_DCC_count$n_DCC,
ci=mortality_ICC_DCC_count$n_event_ICC,
di = mortality_ICC_DCC_count$n_ICC- mortality_ICC_DCC_count$n_event_ICC,
n2i = mortality_ICC_DCC_count$n_ICC,
slab=paste(mortality_ICC_DCC_count$Trial_id, sep=" "))

```

```{r fitting regression model for two stage}

tidy.logistf <- function(x,conf.int = TRUE, conf.level = 0.95, ...) {
  
  trash <- utils::capture.output(s <- summary(x))
  ret <- tibble(
    term = names(s$coefficients),
    estimate = s$coefficients,
    std.error = sqrt(diag(s$var)),
    p.value = s$prob)
  
  if (conf.int) {
    if (conf.level != x$conflev) {
      warning("Models of class `logistf` do not allow `glance` to modify the alpha level after fitting the model. Please use the `alpha` argument of the `logistf::logistf` function.")
    }
    
    ci <- confint(x, level = conf.level)
    ci <- tibble::tibble(
      term = row.names(ci),
      conf.low = ci[, 1],
      conf.high = ci[, 2])
    
    ret <- dplyr::left_join(ret, ci, by = "term")
  }
  
  ret
}

mortality_ICC_DCC_gee <-
  ICC_DCC %>% 
  filter(!is.na(death_discharge_new)) %>% 
  mutate(death_discharge_new = death_discharge_new %>%
           as.character %>% as.numeric(),
         treatment_cat = treatment_cat %>% 
           relevel(ref = "ICC"),
         # sex = sex %>% as.factor %>% relevel(ref = "1"),
         mat_ID = mat_ID %>% as.factor()) %>% 
  # select(Trial_id,infant_ID,mat_ID)
  arrange(mat_ID)

aus_tarnow_mordi_2017_two <-
  geeglm(death_discharge_new ~ treatment_cat  + GA,
      data =
          mortality_ICC_DCC_gee[mortality_ICC_DCC_gee$Trial_id == 
                                  "aus_tarnow_mordi_2017",],
      id = mat_ID,
      family = binomial("logit"),
      control = geese.control(maxit = 100)
      ) %>%
  tidy() %>% 
  mutate(slab = "aus_tarnow_mordi_2017")

canada_murphy_two <- logistf (death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "canada_murphy_2007",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="canada_murphy_2007")

egypt_allam_2018_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "egypt_allam_2018",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="egypt_allam_2018")

egypt_nour_2020_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "egypt_nour_2020",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="egypt_nour_2020")

india_agarwal_2019_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "india_agarwal_2019",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="india_agarwal_2019")

india_datta_2017_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "india_datta_2017",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="india_datta_2017")

india_ranjit_2013_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "india_ranjit_2013",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="india_ranjit_2013")

israel_kugelman_2007_two <- logistf (death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "israel_kugelman_2007",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="israel_kugelman_2007")

spain_carbonell_2014_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "spain_carbonell_2014",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="spain_carbonell_2014")

spain_depaco_2011_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "spain_depaco_2011",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="spain_depaco_2011")

uk_duley_2017_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "uk_duley_2017",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="uk_duley_2017")

usa_backes_2016_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "usa_backes_2016",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="usa_backes_2016")

usa_oh_2011_two <- logistf(death_discharge_new ~ treatment_cat + GA, data = ICC_DCC [ICC_DCC$Trial_id == "usa_oh_2011",], family = binomial("logit")) %>% tidy() %>% mutate(slab ="usa_oh_2011")

merged_two <- 
  dplyr::bind_rows(aus_tarnow_mordi_2017_two,canada_murphy_two,
            egypt_nour_2020_two,
            egypt_allam_2018_two, india_agarwal_2019_two, india_datta_2017_two,
            india_ranjit_2013_two,
            israel_kugelman_2007_two,
            spain_carbonell_2014_two,
            spain_depaco_2011_two,usa_backes_2016_two,
            uk_duley_2017_two,
            usa_oh_2011_two)  %>% 
  filter(term == "treatment_catDCC") %>% 
    arrange(slab)

```

```{r two stage meta analysis}
mortality_ICC_DCC_count_merged <- 
  counts %>% 
  left_join(merged_two,by = "slab")


IPD_icc_dcc_death_df <- 
  escalc(yi = estimate, 
         sei = std.error, 
         ai= n_events_DCC,
         bi = n_DCC - n_event_DCC, 
         n1i = n_DCC ,
         ci= n_event_ICC, 
         di = n_ICC - n_event_ICC, 
         n2i = n_ICC,
         data = mortality_ICC_DCC_count_merged)
IPD_icc_dcc_death_df <- IPD_icc_dcc_death_df %>% mutate(alloc = rev(seq(2, (nrow(IPD_icc_dcc_death_df)+1))) )

res.IPD <- rma(yi, vi,  data = IPD_icc_dcc_death_df, method="FE",
         ai= n_events_DCC,
           bi = n_DCC - n_event_DCC, 
           n1i = n_DCC ,
           ci= n_event_ICC, 
           di = n_ICC  - n_event_ICC, 
           n2i = n_ICC, 
           slab=paste((mortality_ICC_DCC_count_merged$slab), sep=" "))

predict (res.IPD, transf = exp, digits=2)
```

```{r}

# AG data summaries

tbl_icc_dcc <- tbl  %>% group_by(Trial_ID) %>% filter((sum(tbl$Treatment=="1", na.rm=T)>0)&(sum( grepl("2|3|4|9", tbl$Treatment), na.rm=T)>0)) %>% ungroup 
tbl_icc_dcc <- tbl_icc_dcc %>% filter(grepl("1|2|3|4|9", tbl$Treatment))

tbl_icc_ucm <- tbl  %>% group_by(Trial_ID) %>% filter((sum(tbl$Treatment=="1", na.rm=T)>0)&(sum(grepl("5|6|7|8", tbl$Treatment), na.rm=T)>0)) %>% ungroup 
tbl_icc_ucm <- tbl_icc_ucm %>% filter(grepl("1|5|6|7|8", tbl$Treatment))


tbl_dcc_ucm <-  tbl  %>% group_by(Trial_ID) %>% filter((sum(grepl("2|3|4|9", tbl$Treatment), na.rm=T)>0)&(sum(grepl("5|6|7|8", tbl$Treatment), na.rm=T)>0)) %>% ungroup 
tbl_dcc_ucm <- tbl_dcc_ucm %>% filter(grepl("2|3|4|9|5|6|7|8", tbl$Treatment))

tbl_icc_dcc_death <- tbl_icc_dcc %>% filter(grepl("Death",  tbl_icc_dcc$Variable, ignore.case = T))

tbl_icc_dcc_death$events<- tbl_icc_dcc_death$events %>% as.numeric()
tbl_icc_dcc_death$total_binary<- tbl_icc_dcc_death$total_binary %>% as.numeric()


tbl_icc_dcc_death$Treatment2 <- ifelse(grepl("2|3|4|9", tbl_icc_dcc_death$Treatment), "2", ifelse(tbl_icc_dcc_death$Treatment=="1","1",NA))

tbl_icc_dcc_death <- tbl_icc_dcc_death[!is.na(tbl_icc_dcc_death$Treatment2)&tbl_icc_dcc_death$Treatment2!=5,]
tbl_icc_dcc_death <- tbl_icc_dcc_death %>% remove_empty("rows")

tbl_icc_dcc_death<- tbl_icc_dcc_death %>% select(Trial_ID,Treatment2,Variable,total_binary,events)


## getting rid of trials with two of the same categories
tbl_icc_dcc_death<- tbl_icc_dcc_death%>% group_by(Trial_ID) %>% filter(!duplicated(Treatment2,fromLast = TRUE )|duplicated(Treatment2,fromLast = FALSE))
## getting rid of trials no comparison
tbl_icc_dcc_death<- tbl_icc_dcc_death%>% filter(duplicated(Trial_ID,fromLast = TRUE )|duplicated(Trial_ID,fromLast = FALSE))

tbl_icc_dcc_death_wide <- tbl_icc_dcc_death %>% tidyr::pivot_wider(names_from = Treatment2, values_from = c(total_binary, events)) 

#tbl_icc_dcc_death_sum <- data.frame(proportion_2dead = tbl_icc_dcc_death_wide$events_2/tbl_icc_dcc_death_wide$total_binary_2,
#                                   proportion_1dead = tbl_icc_dcc_death_wide$events_1/tbl_icc_dcc_death_wide$total_binary_1)


#dat <- data.frame(proportion2overallmean = mean(tbl_icc_dcc_death_sum$proportion_2dead),
#           proportion1overallmean = mean(tbl_icc_dcc_death_sum$proportion_1dead))


ag_icc_dcc_death_df <- escalc( measure = "OR",   
                                   ai= tbl_icc_dcc_death_wide$events_2,
                                   bi =tbl_icc_dcc_death_wide$total_binary_2 - tbl_icc_dcc_death_wide$events_2, 
                                   n1i =tbl_icc_dcc_death_wide$total_binary_2 ,
                                   ci=tbl_icc_dcc_death_wide$events_1, 
                                   di = tbl_icc_dcc_death_wide$total_binary_1- tbl_icc_dcc_death_wide$events_1, 
                                   n2i = tbl_icc_dcc_death_wide$total_binary_1,
                                slab=paste(tbl_icc_dcc_death_wide$Trial_ID, sep=" "),  drop00=TRUE)

res.AD <- rma(yi, vi, data=ag_icc_dcc_death_df,  method="FE")

ag_icc_dcc_death_df$data_type <- "AG data"
ag_icc_dcc_death_df$data_type_code <- 1

```

```{r}
ag_counts <- data.frame(   
                                   ai= tbl_icc_dcc_death_wide$events_1,
                                   bi =tbl_icc_dcc_death_wide$total_binary_1- tbl_icc_dcc_death_wide$events_1, 
                                   n1i =tbl_icc_dcc_death_wide$total_binary_1 ,
                                   ci=tbl_icc_dcc_death_wide$events_2, 
                                   di = tbl_icc_dcc_death_wide$total_binary_2- tbl_icc_dcc_death_wide$events_2, 
                                   n2i = tbl_icc_dcc_death_wide$total_binary_2,
                                slab=paste(tbl_icc_dcc_death_wide$Trial_ID, sep=" "))

ag_icc_dcc_death_df$slab <- ag_counts$slab

count <- rbind(counts, ag_counts)

IPD_icc_dcc_death_df$data_type <- "IPD data"
IPD_icc_dcc_death_df$data_type_code <- 2

IPD_icc_dcc_death_df <- IPD_icc_dcc_death_df %>% select (yi, vi, data_type, data_type_code, slab)

combined_icc_dcc <- rbind(IPD_icc_dcc_death_df , ag_icc_dcc_death_df )
combined_icc_dcc$alloc <- rev(seq(1, nrow(combined_icc_dcc)))

```

```{r fig.height= 14, fig.width=18, dpi=500}
#change the left bound after you have run the forest plot once
left_bound <- -14.5
#change the right bound after you have run the forest plot once
right_bound <-8

rma1 <- rma(yi = combined_icc_dcc$yi, vi =combined_icc_dcc$vi, method="FE")

mlabfun <- function(text, res) {
   list(bquote(paste(.(text),
      " (Q = ", .(formatC(res$QE, digits=2, format="f")),
      ", df = ", .(res$k - res$p),
      ", p ", .(metafor:::.pval(res$QEp, digits=2, showeq=TRUE, sep=" ")), "; ",
      I^2, " = ", .(formatC(res$I2, digits=1, format="f")), "%, ",
      tau^2, " = ", .(formatC(res$tau2, digits=2, format="f")), ")")))}

#keep in trials with 0 0 events in
options(na.action = "na.pass")

k <- nrow(combined_icc_dcc)
kIPD <- combined_icc_dcc %>% filter(data_type =="IPD data") %>% nrow()
kag <- combined_icc_dcc %>% filter(data_type =="AG data") %>% nrow()


#keep in trials with 0 0 events in
  options(na.action = "na.pass")
sav <- forest(rma1, atransf=exp, 
              rows=c(3:10,13:32), 
              xlab ="Odds ratio (log scale)", order =combined_icc_dcc$alloc, 
              ylim=c(-1,35), xlim=c(left_bound,right_bound),
                #alim = c(log(0.05), log(20)), cex=1.3, 
              showweights = TRUE,
              ilab=cbind(paste(count$ai, "/", count$n1i), paste( count$ci,"/",count$n2i)),
              ilab.xpos=seq(-6.5, -5.5, length = 2), slab=combined_icc_dcc$slab,
              header = FALSE, annotate = TRUE
              )
### add summary polygons for the three subgroups
addpoly(res.IPD, row=(3.5+kag), mlab= mlabfun("FE Model for Subgroup", res.IPD), cex=1)
addpoly(res.AD, row=1.5, mlab= mlabfun("FE Model for Subgroup", res.AD), cex=1)

text(-13.2, c((kag+3),(k+5)), pos=1, cex=0.85, c("Aggregate data", "Individual participant data"), font = 4)

text(left_bound, k+7, pos=4, cex=1.3, c("AD vs IPD Meta-analysis - Death discharge"), font = 4)
text(c(mean(sav$ilab.xpos[1:1.5]),mean(sav$ilab.xpos[2:2.5])), k+6.5, c("DCC", "ICC"), pos=1, cex=1.3)
text(sav$ilab.xpos, (k+5.8), pos=1, c("(n/N)","(n/N)"), cex = 1.1, font =3)
text(8,                     34, "Odds Ratio [95% CI]", cex=1.3, pos = 2)
text(-12.8,                     34, "Study", cex=1.3, pos = 2) 
text(c(log(0.05),log(20)), -1, pos=1, c("Favours DCC", "Favours ICC"), cex=1) 

### fit meta-regression model to test for subgroup differences
res <- rma(yi, vi, mods = ~ data_type, data=combined_icc_dcc, method="FE" #,slab = Trial_id
           )

### add text for the test of subgroup differences
text(-14.5, 0.5, pos=4, cex=1, bquote(paste("Test for Subgroup Differences: ",
     Q[M], " = ", .(formatC(res$QM, digits=2, format="f")), ", df = ", .(res$p - 1),
     ", p = ", .(formatC(res$QMp, digits=2, format="f")))))
### add 'Not estimable' for study with missing log odds ratio
text(sav$textpos[2], k+5-which(is.na(combined_icc_dcc$yi)&combined_icc_dcc$data_type_code==2), "Not estimable", pos=2, cex=1)

```